variable "name_prefix" {
  description = "Prefix applied to RDS resources."
  type        = string
}

variable "database_subnet_ids" {
  description = "Private database subnet IDs used by the DB subnet group."
  type        = list(string)

  validation {
    condition     = length(var.database_subnet_ids) >= 2
    error_message = "At least two database subnets are required."
  }
}

variable "security_group_id" {
  description = "Security group that permits PostgreSQL only from ECS."
  type        = string
}

variable "database_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "nestforge"
}

variable "database_username" {
  description = "PostgreSQL master username."
  type        = string
}

variable "database_password" {
  description = "PostgreSQL master password generated by the secrets module."
  type        = string
  sensitive   = true
}

variable "database_port" {
  description = "PostgreSQL listener port."
  type        = number
  default     = 5432
}

variable "engine_version" {
  description = "Supported PostgreSQL major version. AWS applies compatible minor upgrades."
  type        = string
  default     = "17"
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial gp3 storage allocation in GiB."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Maximum gp3 storage allocation in GiB for autoscaling."
  type        = number
  default     = 100
}

variable "multi_az" {
  description = "Whether RDS maintains a synchronous standby in another AZ."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Number of days automated backups are retained."
  type        = number
  default     = 7
}

variable "deletion_protection" {
  description = "Whether RDS deletion protection is enabled."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Whether to skip a final snapshot during DB deletion."
  type        = bool
  default     = true
}

variable "maintenance_window" {
  description = "Preferred weekly maintenance window in UTC."
  type        = string
  default     = "sun:04:00-sun:05:00"
}

variable "backup_window" {
  description = "Preferred daily backup window in UTC."
  type        = string
  default     = "02:00-03:00"
}
